{% set name = "cca-babel" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://computation.llnl.gov/casc/components/docs/babel-2.0.0.tar.gz
  fname: babel-2.0.0.tar.gz
  patches:
    - override-java.patch [unix]

requirements:
  build:
    - python >=2.7.13,<3
    - numpy
    - libxml2
    - gcc
    - isl <=0.12.2
    - libgcc
    - libgfortran
    - chasm
    - libparsifal
    - libtool
    - pkg-config [osx]

  run:
    - python >=2.7.13,<3
    - numpy
    - libxml2
    - gcc
    - isl <=0.12.2
    - libgcc
    - libgfortran
    - chasm
    - libparsifal
    - libtool
    - pkg-config [osx]

build:
  number: 1

about:
  home: https://github.com/csdms/cca-babel
  summary: |
    Babel is a language interoperability tool intended for use by
    the high-performance scientific computing community.
  license: GNU Lesser General Public License v2.1
